### PR TITLE
Addition and migration to 2.4

### PR DESCRIPTION
**Pull request by theflakes**
Getting back to working on a script to detect DNS badness.  I welcome anyone's help with this.  I started this months ago and now have some time to start working on it again.

Also updated things for Bro 2.4.

### CODE REVIEW

**Comment by theflakes** [comment]
Sorry I did not check your branch before the pull req.  Let me know if you want me to redo the pull and remove the 2.4-scripts folder.

**Comment by sooshie** [comment]
Thanks for doing this, sorry it took a while to get to it. Feel free to re-PR if it you'd like.

**Comment by theflakes** [comment]
Ok, I saw that you had done some work and I didn't want it to interfere
with what you had done.  I will re-submit.  thanks

**Comment by sooshie** [comment]
No sweat, it looked good, I just changed a bit of syntax where it seemed to need it to bring things up with 2.4. Should be good for a while (or until 2.5 is released).

**Pull request closed without merging**
